---
apiVersion: "scheduling.k8s.io/v1"
description: "Used for Nirmata app services with higher priority."
kind: "PriorityClass"
metadata:
  name: "nirmata-app-critical"
  namespace: {{ include "helmchart.namespace" . | quote }}
  labels: {}
value: 900000
