apiVersion: v1
data:
  MONGODB_URI: {{ printf "mongodb://mongodb-hs.%s" (include "helmchart.namespace" .) | b64enc | quote }}
kind: Secret
metadata:
  name: mongodb-uri
  namespace: {{ include "helmchart.namespace" . | quote }}
type: Opaque
