apiVersion: v1
data:
  tls.crt: {{ .Values.global.secrethelm.data.tlscrt }}
  tls.key: {{ .Values.global.secrethelm.data.tlskey }}
  server.crt: {{ .Values.global.secrethelm.data.tlscrt }}
  server.key: {{ .Values.global.secrethelm.data.tlskey }}
kind: Secret
metadata:
  name: tls-certificate
  namespace: {{ include "helmchart.namespace" . | quote }}
type: kubernetes.io/tls
