apiVersion: v1
data:
  api: aHR0cHM6Ly9haS1ib3Jpc2FpOTQzMzI1OTY3NzI0Lm9wZW5haS5henVyZS5jb20v
  key: NzJkODUxOTgxZDViNGQwYTk0OGM3MTFlZmVjMjA5Nzg=
kind: Secret
metadata:
  name: policy-studio-ai
  namespace: {{ include "helmchart.namespace" . | quote }}