apiVersion: v1
kind: Secret
metadata:
  name: mongo-truststore-keystore 
  namespace: {{ include "helmchart.namespace" . | quote }}
data:
{{- if .Values.global.mongo.hostedMongo }}
  truststore: {{ .Files.Get "files/truststore" | b64enc | quote }}
  keystore: {{ .Files.Get "files/keystore" | b64enc | quote }}
{{- else }}
  # Default empty truststore/keystore for Community Operator setup
  truststore: {{ "placeholder-truststore" | b64enc | quote }}
  keystore: {{ "placeholder-keystore" | b64enc | quote }}
{{- end }}
type: Opaque
