{{ if .Values.global.mongo.hostedMongo }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-truststore-credentials
  namespace: {{ include "helmchart.namespace" . | quote }}
stringData:
  password: {{ .Values.global.mongo.mongoDBTruststorePassword | quote }}
type: Opaque
{{ end }}
