apiVersion: v1
data:
  #echo -n "mongoadmin" | base64
  # Update value by running the command echo -n <username> | base64
  username: {{ default "" .Values.global.mongo.mongoDBUsername | b64enc | quote }}
  #echo -n "adminpassword" | base64
  # Update value by running the command echo -n <password> | base64
  password:  {{ default "" .Values.global.mongo.mongoDBPassword | b64enc | quote }}
kind: Secret
metadata:
  name: mongo-credentials
  namespace: {{ include "helmchart.namespace" . | quote }}
type: Opaque
