{{- if not .Values.global.mongo.hostedMongo }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: {{ include "helmchart.namespace" . | quote }}
imagePullSecrets:
- name: {{ .Values.global.imagePullSecrets.name | default "image-registry" }}
secrets:
- name: mongodb-token-r7kff
{{- end }}
