apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-service
  namespace: {{ include "helmchart.namespace" . | quote }}
automountServiceAccountToken: false
imagePullSecrets:
- name: {{ .Values.global.imagePullSecrets.name | default "registry-secret" }}