---
apiVersion: "policy/v1"
kind: "PodDisruptionBudget"
metadata:
  annotations: {}
  name: "gateway-service-pdb"
  namespace: {{ include "helmchart.namespace" . | quote }}
  labels: {}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      nirmata.io/service.name: "gateway-service"
    matchExpressions: []