---
apiVersion: "policy/v1"
kind: "PodDisruptionBudget"
metadata:
  name: "policies-event-processor-pdb"
  namespace: {{ include "helmchart.namespace" . | quote }}
  labels: {}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      nirmata.io/service.name: "policies-event-processor"
    matchExpressions: []
