---
apiVersion: "policy/v1"
kind: "PodDisruptionBudget"
metadata:
  name: "client-gateway-pdb"
  namespace: {{ include "helmchart.namespace" . | quote }}
  labels: {}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      nirmata.io/service.name: "client-gateway"
    matchExpressions: []
