apiVersion: v1
imagePullSecrets:
- name: {{ .Values.global.imagePullSecrets.name | quote }}
kind: ServiceAccount
metadata:
  name: gateway-service
  namespace: {{ include "helmchart.namespace" . | quote }}
automountServiceAccountToken: false