---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  name: "gateway-service"
  namespace: {{ include "helmchart.namespace" . | quote }}
  labels:
    nirmata.io/service.name: "gateway-service"
    nirmata.io/component: "gateway-service"
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    nirmata.io/service.name: "gateway-service"
    nirmata.io/component: "gateway-service"
  ports:
  - port: 443
    protocol: "TCP"
    targetPort: 8443