apiVersion: "v1"
kind: "Service"
metadata:
  name: "llm-apps"
  namespace: {{ include "helmchart.namespace" . | quote }}
  labels:
    nirmata.io/service.name: "llm-apps"
spec:
  type: "ClusterIP"
  selector:
    nirmata.io/service.name: "llm-apps"
  ports:
  - name: "https"
    port: 443 
    protocol: "TCP"
    targetPort: 8443
