apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: {{ .Values.global.imagePullSecrets.name | quote }}
metadata:
  name: clientgateway-service
  namespace: {{ include "helmchart.namespace" . | quote }}
automountServiceAccountToken: false
