{{- if .Values.users.enabled }}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: {{ .Values.global.imagePullSecrets.name | quote }}
metadata:
  name: users-service
  namespace: {{ include "helmchart.namespace" . | quote }}
automountServiceAccountToken: false
{{- end }}
