apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nch-step1-prerequisites
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nch-charts
  source:
    repoURL: https://github.com/anuddeeph1/nch-using-argocd.git
    targetRevision: HEAD
    path: nch-charts
    helm:
      valueFiles:
        - ../config/values/base.yaml
        - ../config/values/environments/dev.yaml  # Change to prod.yaml for production
        - ../config/values/steps/prerequisites.yaml
      parameters:
        - name: prereq.enabled
          value: "true"
        - name: base.enabled
          value: "false"
        - name: others.enabled
          value: "false"
        - name: postreq.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: nch-dev1  # Change to nch-pe for production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: v1
      kind: Secret
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/deployment.kubernetes.io~1revision
