apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nch-step2-data-services-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nch-charts
  source:
    repoURL: https://github.com/anuddeeph1/nch-using-argocd.git
    targetRevision: HEAD
    path: nch-charts
    helm:
      valueFiles:
        - ../config/values/base.yaml
        - ../config/values/environments/prod.yaml
        - ../config/values/steps/data-services.yaml
      parameters:
        - name: prereq.enabled
          value: "false"
        - name: base.enabled
          value: "true"
        - name: others.enabled
          value: "false"
        - name: postreq.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: nch-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
  ignoreDifferences:
    # Ignore service account tokens completely
    - group: v1
      kind: Secret
      jqPathExpressions:
        - 'select(.type == "kubernetes.io/service-account-token")'
    # And ignore StatefulSet storage and status
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        - /status
        - /metadata/generation
        - /metadata/resourceVersion
    # And ignore PVC storage
    - group: v1
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/resources/requests/storage
    - group: v1
      kind: Secret
      name: mongodb-token-*
      jsonPointers:
        - /data